image: django

all_tests:
  script:
   - sh ./sh_scripts/install.sh
   - coverage run --source='.' manage.py test -k
   - coverage report
  when: on_success
  only:
    - master
    - dev
    - refactor