# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True)),
                ('name', models.TextField(max_length=100)),
                ('student_id', models.TextField(max_length=100)),
                ('gender', models.TextField(max_length=100)),
                ('major', models.TextField(max_length=100)),
                ('phone_number', models.TextField(max_length=100)),
                ('self_intro', models.TextField(max_length=100)),
                ('question_one', models.TextField(max_length=1000)),
                ('question_two', models.TextField(max_length=1000)),
                ('inclination_one', models.TextField(max_length=100)),
                ('inclination_two', models.TextField(max_length=100)),
                ('share_work', models.TextField(max_length=100)),
                ('photo', models.TextField(max_length=100)),
            ],
        ),
    ]
