# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160726_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_name', models.TextField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('profession_rate', models.TextField(max_length=20)),
                ('cooperation_rate', models.TextField(max_length=20)),
                ('general_rate', models.TextField(max_length=20)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclination_one_time', models.TextField(max_length=100)),
                ('inclination_two_time', models.TextField(max_length=100)),
                ('star_amount', models.IntegerField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='personinfo',
            name='star_amount',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='management',
            name='person_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PersonInfo'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='person_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PersonInfo'),
        ),
    ]
