# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160728_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='star_amount',
        ),
        migrations.AddField(
            model_name='management',
            name='if_star',
            field=models.BooleanField(default=False),
        ),
    ]
