# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160728_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='star_amount',
            field=models.IntegerField(default=0),
        ),
    ]
