# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160728_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='person_name',
        ),
        migrations.AddField(
            model_name='personinfo',
            name='inc_one_time',
            field=models.TextField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='inc_two_time',
            field=models.TextField(default='0', max_length=100),
        ),
        migrations.DeleteModel(
            name='Management',
        ),
    ]
