# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160728_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_value', models.TextField()),
                ('expire_time', models.IntegerField(default=1)),
                ('is_valid', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
