# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160806_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='cooperation_rate',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='general_rate',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='profession_rate',
            field=models.IntegerField(max_length=20),
        ),
    ]
