# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160823_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='cooperation_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='general_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='profession_rate',
            field=models.IntegerField(),
        ),
    ]
