# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160823_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='grade',
            field=models.TextField(default='1', max_length=100),
        ),
    ]
