# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_personinfo_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='is_spam',
        ),
        migrations.AddField(
            model_name='assessment',
            name='average_cooper',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='average_general',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='average_pro',
            field=models.FloatField(default=5.0),
        ),
    ]
