# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160826_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='is_spam',
            field=models.TextField(default='false'),
        ),
    ]
