# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160826_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='total_marks',
            field=models.FloatField(default=25.0),
        ),
    ]
