# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_personinfo_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
