# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_assessment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='department',
            field=models.ManyToManyField(to='api.Department'),
        ),
    ]
