# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_personinfo_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='assess_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='average_cooper',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='department',
            name='average_expression',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='department',
            name='average_general',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='department',
            name='average_interesting',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='department',
            name='average_pro',
            field=models.FloatField(default=5.0),
        ),
    ]
