# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_personinfo_mail_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='assess_count',
        ),
        migrations.RemoveField(
            model_name='department',
            name='average_cooper',
        ),
        migrations.RemoveField(
            model_name='department',
            name='average_expression',
        ),
        migrations.RemoveField(
            model_name='department',
            name='average_general',
        ),
        migrations.RemoveField(
            model_name='department',
            name='average_interesting',
        ),
        migrations.RemoveField(
            model_name='department',
            name='average_pro',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
